/**
* This file was automatically generated by @cosmwasm/ts-codegen@1.9.0.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

export interface InstantiateMsg {
  cw721_code_id: number;
  transceiver_hub: string;
}
export type ExecuteMsg = {
  accept_admin_role: {};
} | {
  update_config: {
    admin?: string | null;
  };
} | {
  create_collection: {
    name: string;
  };
} | {
  mint: {
    collection: string;
    recipient: string;
    token_list: string[];
  };
} | {
  burn: {
    collection: string;
    token_list: string[];
  };
};
export type QueryMsg = {
  config: {};
} | {
  collection: {
    address: string;
  };
} | {
  collection_list: {
    amount: number;
    start_after?: string | null;
  };
};
export interface MigrateMsg {
  version: string;
}
export type String = string;
export type Addr = string;
export type ArrayOfTupleOfAddrAndString = [Addr, string][];
export interface Config {
  admin: Addr;
  cw721_code_id: number;
  transceiver_hub: Addr;
}