/**
* This file was automatically generated by @cosmwasm/ts-codegen@1.9.0.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

import { Coin } from "@cosmjs/amino";
import { MsgExecuteContractEncodeObject } from "@cosmjs/cosmwasm-stargate";
import { MsgExecuteContract } from "cosmjs-types/cosmwasm/wasm/v1/tx";
import { toUtf8 } from "@cosmjs/encoding";
import { InstantiateMsg, ExecuteMsg, QueryMsg, MigrateMsg, Uint64, Addr, Config, Uint128, QueryPricesResponse, PriceItem } from "./Oracle.types";
export interface OracleMsg {
  contractAddress: string;
  sender: string;
  acceptAdminRole: (_funds?: Coin[]) => MsgExecuteContractEncodeObject;
  updateConfig: ({
    admin,
    controller,
    executionCooldown,
    maxPriceUpdatePeriod,
    worker
  }: {
    admin?: string;
    controller?: string[];
    executionCooldown?: number;
    maxPriceUpdatePeriod?: number;
    worker?: string;
  }, _funds?: Coin[]) => MsgExecuteContractEncodeObject;
  updatePrices: ({
    data
  }: {
    data: string[][];
  }, _funds?: Coin[]) => MsgExecuteContractEncodeObject;
  removePrices: ({
    collections
  }: {
    collections: string[];
  }, _funds?: Coin[]) => MsgExecuteContractEncodeObject;
}
export class OracleMsgComposer implements OracleMsg {
  sender: string;
  contractAddress: string;
  constructor(sender: string, contractAddress: string) {
    this.sender = sender;
    this.contractAddress = contractAddress;
    this.acceptAdminRole = this.acceptAdminRole.bind(this);
    this.updateConfig = this.updateConfig.bind(this);
    this.updatePrices = this.updatePrices.bind(this);
    this.removePrices = this.removePrices.bind(this);
  }
  acceptAdminRole = (_funds?: Coin[]): MsgExecuteContractEncodeObject => {
    return {
      typeUrl: "/cosmwasm.wasm.v1.MsgExecuteContract",
      value: MsgExecuteContract.fromPartial({
        sender: this.sender,
        contract: this.contractAddress,
        msg: toUtf8(JSON.stringify({
          accept_admin_role: {}
        })),
        funds: _funds
      })
    };
  };
  updateConfig = ({
    admin,
    controller,
    executionCooldown,
    maxPriceUpdatePeriod,
    worker
  }: {
    admin?: string;
    controller?: string[];
    executionCooldown?: number;
    maxPriceUpdatePeriod?: number;
    worker?: string;
  }, _funds?: Coin[]): MsgExecuteContractEncodeObject => {
    return {
      typeUrl: "/cosmwasm.wasm.v1.MsgExecuteContract",
      value: MsgExecuteContract.fromPartial({
        sender: this.sender,
        contract: this.contractAddress,
        msg: toUtf8(JSON.stringify({
          update_config: {
            admin,
            controller,
            execution_cooldown: executionCooldown,
            max_price_update_period: maxPriceUpdatePeriod,
            worker
          }
        })),
        funds: _funds
      })
    };
  };
  updatePrices = ({
    data
  }: {
    data: string[][];
  }, _funds?: Coin[]): MsgExecuteContractEncodeObject => {
    return {
      typeUrl: "/cosmwasm.wasm.v1.MsgExecuteContract",
      value: MsgExecuteContract.fromPartial({
        sender: this.sender,
        contract: this.contractAddress,
        msg: toUtf8(JSON.stringify({
          update_prices: {
            data
          }
        })),
        funds: _funds
      })
    };
  };
  removePrices = ({
    collections
  }: {
    collections: string[];
  }, _funds?: Coin[]): MsgExecuteContractEncodeObject => {
    return {
      typeUrl: "/cosmwasm.wasm.v1.MsgExecuteContract",
      value: MsgExecuteContract.fromPartial({
        sender: this.sender,
        contract: this.contractAddress,
        msg: toUtf8(JSON.stringify({
          remove_prices: {
            collections
          }
        })),
        funds: _funds
      })
    };
  };
}