/**
* This file was automatically generated by @cosmwasm/ts-codegen@1.9.0.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

export interface InstantiateMsg {
  controller?: string[] | null;
  execution_cooldown?: number | null;
  max_price_update_period?: number | null;
  worker?: string | null;
}
export type ExecuteMsg = {
  accept_admin_role: {};
} | {
  update_config: {
    admin?: string | null;
    controller?: string[] | null;
    execution_cooldown?: number | null;
    max_price_update_period?: number | null;
    worker?: string | null;
  };
} | {
  update_prices: {
    data: [string, number][];
  };
} | {
  remove_prices: {
    collections: string[];
  };
};
export type QueryMsg = {
  query_config: {};
} | {
  query_prices: {
    amount: number;
    collections?: string[] | null;
    start_after?: string | null;
  };
} | {
  query_block_time: {};
};
export interface MigrateMsg {
  version: string;
}
export type Uint64 = number;
export type Addr = string;
export interface Config {
  admin: Addr;
  controller: Addr[];
  execution_cooldown: number;
  max_price_update_period: number;
  worker: Addr;
}
export type Uint128 = string;
export interface QueryPricesResponse {
  data: PriceItem[];
  is_outdated: boolean;
}
export interface PriceItem {
  collection: Addr;
  price: Uint128;
}