/**
* This file was automatically generated by @cosmwasm/ts-codegen@1.9.0.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

export interface InstantiateMsg {
  execution_cooldown?: number | null;
  lending_platform?: string | null;
  offchain_clock?: string[] | null;
  worker?: string | null;
}
export type ExecuteMsg = {
  accept_admin_role: {};
} | {
  update_config: {
    admin?: string | null;
    execution_cooldown?: number | null;
    lending_platform?: string | null;
    offchain_clock?: string[] | null;
    worker?: string | null;
  };
} | {
  push: {
    targets: LiquidationItem[];
  };
};
export type Uint128 = string;
export type Decimal = string;
export type BidType = "liquidation_bid" | "collection_offer";
export type Addr = string;
export interface LiquidationItem {
  borrower: string;
  liquidation_set: BiddedCollateralItem[];
}
export interface BiddedCollateralItem {
  bid_amount: Uint128;
  bid_creation_date: number;
  bid_discount: Decimal;
  bid_type: BidType;
  collateral_price: Uint128;
  collection: Addr;
  liquidation_price: Uint128;
  liquidator: Addr;
  owner: Addr;
  token_item: TokenItem;
}
export interface TokenItem {
  creation_date: number;
  id: string;
}
export type QueryMsg = {
  query_config: {};
} | {
  query_log: {};
};
export interface MigrateMsg {
  version: string;
}
export interface Config {
  admin: Addr;
  execution_cooldown: number;
  lending_platform: Addr;
  offchain_clock: Addr[];
  worker?: Addr | null;
}
export type ArrayOfLog = Log[];
export interface Log {
  block_time: number;
  counter: number;
  sender: Addr;
}